name: Deploy Backend to Cloud Run

on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: cardly-devops
  GAR_LOCATION: asia-southeast1
  REPOSITORY: cardly-backend-repo
  SERVICE: cardly-backend
  REGION: asia-southeast1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud via OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Container
        run: |
          docker build -f docker/Dockerfile -t asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--allow-unauthenticated'
          # Chỉ để lại các cấu hình thông thường, các thông tin nhạy cảm được gọi gián tiếp qua secrets
          env_vars: |
            ENVIRONMENT=staging
            APP_VERSION=1.0.0
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            REDIS_URL=redis://localhost:6379/0
            CORS_ORIGINS=["*"]
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_ALG=HS256
            JWT_EXP=15
            REFRESH_TOKEN_EXP=7
            OTP_EXP_MINUTES=10
            SMTP_HOST=smtp.gmail.com
            SMTP_PORT=587
            SMTP_USER=nonamegamingok@gmail.com
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            EMAIL_FROM=okihawa4@gmail.com
            EMAIL_FROM_NAME=cardly
            MAX_SIZE_MB=10
            STORAGE_PATH=/tmp/ocr_uploads
            MIN_DPI=300
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            OCR_ENGINE=gemini
            HIGH_THRESHOLD=0.95
            LOW_THRESHOLD=0.70
